# Generated by Django 5.1.2 on 2024-11-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_date',
            new_name='create_dt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='create_dt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_date',
            new_name='update_dt',
        ),
        migrations.RemoveField(
            model_name='category',
            name='descriptino',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='update_date',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, help_text='simple one-line text.', max_length=100, verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='comment',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='UPDATE DT'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='LIKE'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
